### ISSUE TITLE
Osd Crash with CUDA Compute

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/OpenSubdiv#401]
run glViewer
switch compute to CUDA
select catmark_torus shape
*crash*

```
#5  0x00007ffff266eafe in __cxa_throw () at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:84
#6  0x00007ffff26bf957 in std::__throw_out_of_range(char const*) () at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:80
#7  0x00007ffff6554875 in std::vector<unsigned char, std::allocator<unsigned char> >::_M_range_check(unsigned long) const ()
    at /dist/d2sets/fedora-11-x86_64/tools-base-04/lib/gcc/x86_64-redhat-linux-gnu/4.8.2/include/c++/bits/stl_vector.h:794
#8  0x00007ffff65812a1 in std::vector<unsigned char, std::allocator<unsigned char> >::at(unsigned long) const ()
    at /dist/d2sets/fedora-11-x86_64/tools-base-04/lib/gcc/x86_64-redhat-linux-gnu/4.8.2/include/c++/bits/stl_vector.h:830
#9  0x00007ffff6259bb1 in void* OpenSubdiv::v3_0_0_beta::Osd::createCudaBuffer<unsigned char>(std::vector<unsigned char, std::allocator<unsigned char> > const&) ()
    at opensubdiv/osd/cudaComputeContext.cpp:51
#10 0x00007ffff62599ea in OpenSubdiv::v3_0_0_beta::Osd::CudaComputeContext::CudaStencilTables::CudaStencilTables(OpenSubdiv::v3_0_0_beta::Far::StencilTables const&) ()
    at opensubdiv/osd/cudaComputeContext.cpp:66
#11 0x00007ffff62595cf in OpenSubdiv::v3_0_0_beta::Osd::CudaComputeContext::CudaComputeContext(OpenSubdiv::v3_0_0_beta::Far::StencilTables const*, OpenSubdiv::v3_0_0_beta::Far::StencilTables const*) () at opensubdiv/osd/cudaComputeContext.cpp:115
#12 0x00007ffff625999d in OpenSubdiv::v3_0_0_beta::Osd::CudaComputeContext::Create(OpenSubdiv::v3_0_0_beta::Far::StencilTables const*, OpenSubdiv::v3_0_0_beta::Far::StencilTables const*) () at opensubdiv/osd/cudaComputeContext.cpp:198
#13 0x000000000045bbd0 in OpenSubdiv::v3_0_0_beta::Osd::Mesh<OpenSubdiv::v3_0_0_beta::Osd::CudaGLVertexBuffer, OpenSubdiv::v3_0_0_beta::Osd::CudaComputeController, OpenSubdiv::v3_0_0_beta::Osd::GLDrawContext>::initializeComputeContext(int, int) () at opensubdiv/osd/glMesh.h:198
#14 0x0000000000458ad1 in OpenSubdiv::v3_0_0_beta::Osd::Mesh<OpenSubdiv::v3_0_0_beta::Osd::CudaGLVertexBuffer, OpenSubdiv::v3_0_0_beta::Osd::CudaComputeController, OpenSubdiv::v3_0_0_beta::Osd::GLDrawContext>::Mesh(OpenSubdiv::v3_0_0_beta::Osd::CudaComputeController*, OpenSubdiv::v3_0_0_beta::Far::TopologyRefiner*, int, int, int, std::bitset<5ul>) ()
    at opensubdiv/osd/glMesh.h:76
#15 0x000000000044cb39 in createOsdMesh(ShapeDesc const&, int, int, Scheme) () at examples/glViewer/glViewer.cpp:609
#16 0x00000000004513e9 in rebuildOsdMesh() () at examples/glViewer/glViewer.cpp:1484
```

**Comment by manuelk** [comment]
Windows debug build ? if so - it's just STL having a hissy fit (not that the code shouldn't be fixed...)

**Comment by jcowles** [comment]
OSX -- Takahito suspects empty stencil tables is the cause.

--
Jeremy

**Comment by manuelk** [comment]
Torus shape ? Should be working... but it's been a while

**Comment by jcowles** [comment]
@takahito-tejima, did you already check in a fix for this?

**Comment by takahito-tejima** [comment]
Yes, 24a435da013a129985a06739b6964b316b3e4ed6 fixed it. closeing.
